defaults: &defaults
  backlog:
    base_url: https://bibo-mng.backlog.jp
    api:
      count:  /api/v2/issues/count
      issue:  /api/v2/issues/%s
      issues: /api/v2/issues
    path:
      view: /view/%s


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
